language: python
python:
  - "2.7"

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls
  - cp flaskapp/config.example.py flaskapp/config.py

# command to run tests
script:
  - cd flaskapp
  - coverage run -m unittest discover

after_success:
    coveralls

