language: python
python:
  - "2.7"

env:
  - SERVER_SETTINGS=../config.example.cfg

# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coveralls

# command to run tests
script: coverage run --source flaskapp --omit '*/venv/*' flaskapp/tests.py

after_success:
    coveralls

